import {User} from './user';
import {ExtraFee} from './extra_fee';

export class Subscription {
  id?: number;
  name: string;
  display_name: string;
  attendance_limited: boolean;
  users?: User[];
  extra_fees: ExtraFee[];
  'description': string;
  'lockin': boolean;
  'plan_duration_name': string;
  'plan_duration': number;
  'limited': boolean;
  'attendance_value': number;
  'auto_renew': number;
  'days_left': number;
  'checkins_left': number;
  'trial_status': boolean;
  'trial_duration': number;
  'trial_duration_name': string;
  'trial_start': string;
  'total_price': number;
  'payment_price': number;
  'frequency_amount': number;
  'frequency_name': string;
  'discount_status': boolean;
  'discount_value': number;
  'discount_value_mark': string;
  'extra_fees_status': boolean;
  'extra_fees_name': string;
  'extra_fees_price': number;
  'extra_fees_condition': string;
  'extra_fees_cancelation_status': number;
  'extra_fees_cancelation_value': number;
  'extra_fees_cancelation_value_name': string;
  'extra_fees_onhold_status': number;
  'extra_fees_onhold_value': number;
  'extra_fees_onhold_maximum_days': number;
  program_id?: number;
  program_name?: string;
  active?: number;
  approved?: number;
  userSubscriptionId?: number;
  scheduledStart?: string;
  paymentPriceWithDiscount?: number;
  subscribedStudentsCount?: number;
}
